#!/bin/bash

# USAGE: `watch-pr <pr_number>`
# Issues a macos desktop notification when the CI the specified PR changes

pr_num=$1

echo "Watching PR $pr_num"

while true; do
    # lol this is so gross
    gh pr checks $pr_num --repo github.com/cockroachdb/cockroach | grep 'GitHub CI' > /dev/null
    if [ $? -eq 0 ]; then
        gh pr checks $pr_num --repo github.com/cockroachdb/cockroach | grep 'pending' > /dev/null
        if [ $? -ne 0 ]; then
            osascript -e "display notification \"Update to PR #$pr_num\" with title \"PR status changed\""
            gh pr checks $pr_num --repo github.com/cockroachdb/cockroach
            echo "PR status changed. Exiting."
            exit 0
        fi
    fi
    sleep 15
done
